services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: next-pocketbase
    restart: unless-stopped
    ports:
      - "8096:8090"
    volumes:  # For CI/CD data persistence use either named volumes or absolute bind mounts.
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_pubdata:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
    # volumes:
    #   - type: bind
    #     source: /mnt/ssd_pool/backups/next_app_data/pb_data
    #     target: /pb_data
    #   - type: bind
    #     source: /mnt/ssd_pool/backups/next_app_data/pb_public
    #     target: /pb_public
    #   - type: bind
    #     source: /mnt/ssd_pool/backups/next_app_data/pb_hooks
    #     target: /pb_hooks
    healthcheck: 
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  frontend:
    container_name: next-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3006:3000"
    networks:
      - app_network

  test-automation:
    container_name: next-test-automation
    build:
      context: ./testAutomation
      dockerfile: dockerfile
    networks:
      - app_network
    depends_on:
     - pocketbase
     - frontend
    restart: "no"

networks:
  app_network:
    driver: bridge